export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const LEVEL_UP='LEVEL_UP';
export const LEVEL_DOWN='LEVEL_DOWN';
export const SELECT_WEAPON="SELECT_WEAPON";
export const SELECT_PLAYER="SELECT_PLAYER";
export const RESET_PLAYER="RESET_PLAYER";
export const SET_PLAYER_NAME="SET_PLAYER_NAME";